#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

$versioner = new Spanky\Versioner\Versioner(getcwd() . '/version');

$app = new Symfony\Component\Console\Application('Versioner');
$app->add(new \Spanky\Versioner\Console\GetVersionCommand($versioner));
$app->add(new \Spanky\Versioner\Console\SetVersionCommand($versioner));
$app->run();
